base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^$',
    views.landing_page,
    name='landing_page'
  ),
  url(
    r'^staff$',
    views.staff,
    name='staff'
  )
]

kury/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^navigation/', include('navigation.urls', namespace='navigation')),
  url(r'^pages/', include('pages.urls', namespace='pages')),
  url(r'^courses/', include('courses.urls', namespace='courses')),
  url(r'^carousel/', include('carousel.urls', namespace='carousel')),
  url(r'^users/', include('users.urls', namespace='users')),
  url(r'^', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^admin$',
    views.admin_index,
    name='admin_index'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)$',
    views.admin_edit,
    name='admin_edit'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/delete$',
    views.admin_delete,
    name='admin_delete'
  ),
  url(
    r'(?P<pk>[0-9]+)/(?P<slug>[-_\w]+)$',
    views.show_page,
    name='show_page'
  )
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^admin$',
    views.admin_index,
    name='admin_index'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)$',
    views.admin_edit,
    name='admin_edit'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/delete$',
    views.admin_delete,
    name='admin_delete'
  ),
  url(
    r'^login$',
    views.login,
    name='login'
  ),
  url(
    r'^logout$',
    views.logout,
    name='logout'
  )
]

kury/templates/kury/admin_layout.html
{% extends 'kury/layout.html' %}

{% block container %}
  <style>
    form.link-submit {
      display: inline;
    }

    form.link-submit .btn-link {
      padding: 0;
    }
  </style>

  <div class="container">
    <br />
    <div class="row">
      <div class="col-xs-2">
        <h4>Kury Admin</h4>
      </div>
      <div class="col-xs-10">
        <ul class="nav nav-tabs pull-right">
          {% with namespace=request.resolver_match.namespaces.0 %}
            <li role="presentation" {% if namespace == 'navigation' %}class="active"{% endif %}>
              <a href="{% url 'navigation:admin_index' %}">Navigation</a>
            </li>
            <li role="presentation" {% if namespace == 'pages' %}class="active"{% endif %}>
              <a href="{% url 'pages:admin_index' %}">Pages</a>
            </li>
            <li role="presentation" {% if namespace == 'courses' %}class="active"{% endif %}>
              <a href="{% url 'courses:admin_index' %}">Courses</a>
            </li>
            <li role="presentation" {% if namespace == 'carousel' %}class="active"{% endif %}>
              <a href="{% url 'carousel:admin_index' %}">Carousel</a>
            </li>
            <li role="presentation" {% if namespace == 'users' %}class="active"{% endif %}>
              <a href="{% url 'users:admin_index' %}">Users</a>
            </li>
            <li role="presentation">
              <a href="{% url 'users:logout' %}">Logout {{ user.username }}</a>
            </li>
          {% endwith %}
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

kury/templates/kury/item_menu_popover.html
{% if parent.children.all|length > 0 %}
  <ul
    class="menu-popover"
    style="display: none;"
    data-kury-popover-parent="#menu-item-{{ parent.pk }}"
    data-kury-popover-position='{"my":"left top","at":"left bottom"}'
    >
      {% for item in parent.children.all %}
        <li>
          {% if item.link %}
            <a href="{{ item.link }}">{{ item.title }}</a>
          {% else %}
            {{ item.title }}
          {% endif %}
        </li>
      {% endfor %}
  </ul>
{% endif %}

kury/templates/kury/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="fi">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kiipeilyurheilijat</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endif %}

      {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
      {% endif %}

      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
      {% endif %}

      {% if message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
      {% endif %}

      {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
        <div class="alert alert-warning" role="alert">{{ message }}</div>
      {% endif %}
    {% endfor %}

    {% block container %}{% endblock %}

    <br />

    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery/jquery.ui.js' %}"></script>
    <script src="{% static 'underscore/underscore.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript">
      $(document).ready(function() {
        kury = {}

        kury.Popover = function($element) {
          this.$element = $element

          this.init()
          this.bind()
        },

        kury.Popover.prototype = {
          init: function() {
            this.$parent = $(this.$element.data('kuryPopoverParent'))

            this.position = this.$element.data('kuryPopoverPosition')
            this.position.of = this.$parent
            this.position.collision = 'flip fit'

            this.$element.appendTo('body')
          },

          bind: function() {
            _.bindAll(this, 'on_mouseover', 'on_mouseout')

            this.$parent.on('mouseover', this.on_mouseover)
            this.$parent.on('mouseout', this.on_mouseout)
          },

          on_mouseover: function(event) {
            this.$element.show().position(this.position)
          },

          on_mouseout: function(event) {
            if( $.contains(this.$element[0], event.relatedTarget) ) {
              this.$element.one('mouseout', this.on_mouseout)
              return
            }

            this.$element.hide()
          }
        },

        $('[data-kury-popover-parent]').each(function(index, element) {
          new kury.Popover( $(element) )
        })

        $('select[data-kury-refresh-form]').each(function(index, input) {
          var $input = $(input)
          var $form = $input.closest('form')

          var on_change = function(event) {
            $.post( $form.attr('action'), $form.serialize() )
              .done(function(data) {
                $form.html(data)
                $form.find('select[data-kury-refresh-form]').on('change', on_change)
              })
          }

          $input.on('change', on_change)
        })
      })
    </script>
  </body>
</html>

kury/templates/kury/site_layout.html
{% extends 'kury/layout.html' %}

{% block container %}
  <style>
    #header {
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 2;
      background-color: rgba(0, 0, 0, 0.7);
    }

    #header h4 {
      color: white;
    }

    .header-offset {
      margin-top: 60px;
    }

    #navigation {
      padding-left: 0;
      margin: 20px 0;
      cursor: default;
    }

    #navigation li {
      font-weight: bold;
      color: #ddd;
      padding: 0 10px;
      display: inline;
    }

    #navigation li:hover {
      color: white;
    }

    #navigation li a {
      color: #ddd;
      text-decoration: none;
    }

    #navigation li a:hover {
      color: white;
      text-decoration: none;
    }

    .menu-popover {
      position: absolute;
      min-width: 200px;
      padding-left: 0;
      background-color: white;
      cursor: default;
      z-index: 1000;
      -webkit-box-shadow: 0px 6px 15px 0px rgba(0,0,0,0.75);
      -moz-box-shadow: 0px 6px 15px 0px rgba(0,0,0,0.75);
      box-shadow: 0px 6px 15px 0px rgba(0,0,0,0.75);
    }

    .menu-popover li {
      list-style: none;
      font-weight: bold;
      color: #999;
    }

    .menu-popover li:hover {
      background-color: #999;
      color: white;
    }

    .menu-popover li a {
      text-decoration: none;
      display: block;
      font-weight: bold;
      color: #999;
      width: 100%;
      padding: 10px;
    }

    .menu-popover li a:hover {
      color: white;
    }

    #carousel {
      width: 100%;
      height: 100%;
    }

    #carousel img {
      width: 100%;
    }
  </style>

  <div id="header">
    <div class="container">
      <div class="row">
        <div class="col-xs-2">
          <h4>Kiipeilyurheilijat</h4>
        </div>
        <div class="col-xs-10">
          <ul id="navigation" class="pull-right">
            {% for item in top_level_items %}
              <li id="menu-item-{{ item.pk }}">
                {% if item.link %}
                  <a href="{{ item.link }}">{{ item.title }}</a>
                {% else %}
                  {{ item.title }}
                {% endif %}
              </li>
              {% include 'kury/item_menu_popover.html' with parent=item %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% block content %}{% endblock %}

{% endblock %}