base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^$',
    views.landing_page,
    name='landing_page'
  ),
  url(
    r'^staff$',
    views.staff,
    name='staff'
  )
]

carousel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^admin$',
    views.admin_index,
    name='admin_index'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)$',
    views.admin_edit,
    name='admin_edit'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/move-up$',
    views.admin_move_up,
    name='admin_move_up'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/move-down$',
    views.admin_move_down,
    name='admin_move_down'
  ),  
  url(
    r'^admin/(?P<pk>[0-9]+)/delete$',
    views.admin_delete,
    name='admin_delete'
  )
]

kury/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^navigation/', include('navigation.urls', namespace='navigation')),
  url(r'^pages/', include('pages.urls', namespace='pages')),
  url(r'^courses/', include('courses.urls', namespace='courses')),
  url(r'^carousel/', include('carousel.urls', namespace='carousel')),
  url(r'^users/', include('users.urls', namespace='users')),
  url(r'^', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carousel/models.py
from __future__ import unicode_literals
from django.db import models
import markdown
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Image(models.Model):
  order_number = models.PositiveIntegerField(
  	verbose_name = 'Order number of the image'
  )
  caption = models.TextField(
    blank = True,
    null = True,
  	verbose_name = 'Caption text for the image',
  	help_text = 'Text to show at the bottom of the image. You may use MarkDown here.'
  )
  image = ProcessedImageField(
  	upload_to = 'carousel',
    processors = [ResizeToFill(640, 480)],
    format = 'JPEG',
    options = {'quality': 90},
  	verbose_name = 'Image file',
  	help_text = 'Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.'
  )

  @classmethod
  def max_order_number(cls):
  	return Image.objects.all().aggregate(models.Max('order_number'))['order_number__max']

  def __unicode__(self):
    return self.caption

  class Meta:
    ordering = ['order_number']

  def __init__(self, *args, **kwargs):
    super(Image, self).__init__(*args, **kwargs)

    if not self.pk:
      self.to_the_end()

  def caption_html(self):
		return markdown.markdown(self.caption, extensions=['markdown.extensions.nl2br'])

  def delete(self, *args, **kwargs):
  	self.slice_off()
  	return super(Image, self).delete(*args, **kwargs)

  def to_the_end(self):
  	max_order_number = Image.max_order_number()

  	self.order_number = 0
  	if max_order_number is not None:
  		self.order_number = max_order_number + 1

  def reorder(self, new_order_number):
  	self.slice_off()
  	self.push_between(new_order_number)

  def slice_off(self):
  	Image.objects.filter(order_number__gt=self.order_number).update(order_number=models.F('order_number') - 1)

  def push_between(self, new_order_number):
  	Image.objects.filter(order_number__gte=new_order_number).exclude(pk=self.pk).update(order_number=models.F('order_number') + 1)

  	self.order_number = new_order_number
  	self.save()

carousel/forms.py
from django import forms
from .models import *

class ImageForm(forms.ModelForm):

  class Meta:
    model = Image
    fields = ('caption', 'image')
    widgets = {
      'caption': forms.Textarea(
        attrs = {
          'class': 'form-control',
          'rows': 15,
        }
      )
    }

carousel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

@login_required
def admin_index(request):
  if request.method == 'POST':
    form = ImageForm(request.POST, request.FILES)

    if form.is_valid():
      form.save()

      messages.success(request, 'New image created!')

      return redirect(reverse('carousel:admin_index'))
    else:
      messages.error(request, 'New image not saved!')
  else:
    form = ImageForm()

  return render(request, 'carousel/admin/index.html', {
    'form': form,
    'images': Image.objects.all(),
  })

@login_required
def admin_edit(request, pk):
  image = get_object_or_404(Image, pk=pk)

  if request.method == 'POST':
    form = ImageForm(request.POST, request.FILES, instance=image)

    if form.is_valid():
      form.save()

      messages.success(request, 'Image saved!')

      return redirect(reverse('carousel:admin_index'))
    else:
      messages.error(request, 'Image not saved!')
  else:
    form = ImageForm(instance=image)

  return render(request, 'carousel/admin/edit.html', {
    'form': form,
    'image': image
  })

@login_required
def admin_delete(request, pk):
  image = get_object_or_404(Image, pk=pk)

  if request.method == 'POST':
    image.delete()
    messages.success(request, 'Image deleted!')

    return redirect(reverse('carousel:admin_index'))

  raise Http404('Not a POST request')

@login_required
def admin_move_up(request, pk):
  image = get_object_or_404(Image, pk=pk)

  if image.order_number == 0:
    raise Http404('Image already the first image')

  if request.method == 'POST':
    image.reorder(image.order_number - 1)

    return redirect(reverse('carousel:admin_index'))

  raise Http404('Not a POST request')

@login_required
def admin_move_down(request, pk):
  image = get_object_or_404(Image, pk=pk)

  if image.order_number == Image.max_order_number():
    raise Http404('Image already the last image')

  if request.method == 'POST':
    image.reorder(image.order_number + 1)
    
    return redirect(reverse('carousel:admin_index'))

  raise Http404('Not a POST request')

carousel/templates/carousel/admin/edit.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Edit image</h1>
<hr />

<div class="row">
  <div class="col-xs-12">
    <form class="pull-right" method="POST" action="{% url 'carousel:admin_delete' pk=image.pk %}">
      {% csrf_token %}
      <input class="btn btn-xs btn-danger" type="submit" value="Delete" />
    </form>
  </div>
</div>

<form method="POST" enctype="multipart/form-data">
  {% include 'carousel/admin/form.html' with form=form %}
</form>
{% endblock %}

carousel/templates/carousel/admin/form.html
{% csrf_token %}

<div class="row">
	<div class="col-xs-12">
	  {% include 'kury/form/input_block.html' with field=form.image %}
	  {% include 'kury/form/input_block.html' with field=form.caption %}
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
	  <br />
	  <input class="btn btn-primary" type="submit" value="Save" />
	</div>
</div>

carousel/templates/carousel/admin/index.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Carousel images</h1>
<hr />

<div class="col-xs-12">
  {% if images|length > 0 %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Image</th>
          <th>Caption</th>
        </tr>
      </thead>
      <tbody>
        {% for image in images %}
          <tr>
            <td>
              <a href="{{ image.image.url }}" target="_blank">Open image</a>
            </td>
            <td>{{ image.caption|truncatewords:10 }}</td>
            <td>
              <a href="{% url 'carousel:admin_edit' pk=image.pk %}">Edit</a>
              {% if not forloop.first %}
                |
                <form class="link-submit" method="POST" action="{% url 'carousel:admin_move_up' pk=image.pk %}">
                  {% csrf_token %}
                  <input class="btn btn-link" type="submit" value="Move up" />
                </form>
              {% endif %}
              {% if not forloop.last %}
                |
                <form class="link-submit" method="POST" action="{% url 'carousel:admin_move_down' pk=image.pk %}">
                  {% csrf_token %}
                  <input class="btn btn-link" type="submit" value="Move down" />
                </form>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-center">No images yet. Create one below!</p>
  {% endif %}
  <br />
</div>

<h2>Create new image</h2>
<hr />

<form method="POST" enctype="multipart/form-data">
  {% include 'carousel/admin/form.html' with form=form %}
</form>

{% endblock %}