base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^$',
    views.landing_page,
    name='landing_page'
  ),
  url(
    r'^staff$',
    views.staff,
    name='staff'
  )
]

kury/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^navigation/', include('navigation.urls', namespace='navigation')),
  url(r'^pages/', include('pages.urls', namespace='pages')),
  url(r'^courses/', include('courses.urls', namespace='courses')),
  url(r'^carousel/', include('carousel.urls', namespace='carousel')),
  url(r'^users/', include('users.urls', namespace='users')),
  url(r'^', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^admin$',
    views.admin_index,
    name='admin_index'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)$',
    views.admin_edit,
    name='admin_edit'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/delete$',
    views.admin_delete,
    name='admin_delete'
  ),
  url(
    r'(?P<pk>[0-9]+)/(?P<slug>[-_\w]+)$',
    views.show_page,
    name='show_page'
  )
]

pages/templates/pages/admin/edit.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Edit page <em>{{ page.title }}</em></h1>
<hr />

<div class="row">
  <div class="col-xs-12">
    <form class="pull-right" method="POST" action="{% url 'pages:admin_delete' pk=page.pk %}">
      {% csrf_token %}
      <input class="btn btn-xs btn-danger" type="submit" value="Delete" />
    </form>
  </div>
</div>

<form method="POST">
  {% include 'pages/admin/form.html' with form=form %}
</form>
{% endblock %}

pages/templates/pages/admin/form.html
{% csrf_token %}

<div class="col-xs-12">
  {% include 'kury/form/input_block.html' with field=form.title %}
  {% include 'kury/form/input_block.html' with field=form.content %}
</div>

<div class="col-xs-12">
  <br />
  <input class="btn btn-primary" type="submit" value="Save" />
</div>

pages/templates/pages/admin/index.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Pages</h1>
<hr />

<div class="col-xs-12">
  {% if pages|length > 0 %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for page in pages %}
          <tr>
            <td>{{ page.title }}</td>
            <td>{{ page.content|truncatewords:30 }}</td>
            <td>
              <a href="{% url 'pages:admin_edit' pk=page.pk %}">Edit</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-center">No pages yet. Create one below!</p>
  {% endif %}
  <br />
</div>

<h2>Create new page</h2>
<hr />

<form method="POST">
  {% include 'pages/admin/form.html' with form=form %}
</form>

{% endblock %}