base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^$',
    views.landing_page,
    name='landing_page'
  ),
  url(
    r'^staff$',
    views.staff,
    name='staff'
  )
]

courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(
    r'^admin$',
    views.admin_index,
    name='admin_index'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)$',
    views.admin_edit,
    name='admin_edit'
  ),
  url(
    r'^admin/(?P<pk>[0-9]+)/delete$',
    views.admin_delete,
    name='admin_delete'
  ),
  url(
    r'^$',
    views.index,
    name='index'
  ),
  url(
    r'^(?P<pk>[0-9]+)',
    views.show,
    name='show'
  )
]

kury/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^navigation/', include('navigation.urls', namespace='navigation')),
  url(r'^pages/', include('pages.urls', namespace='pages')),
  url(r'^courses/', include('courses.urls', namespace='courses')),
  url(r'^carousel/', include('carousel.urls', namespace='carousel')),
  url(r'^users/', include('users.urls', namespace='users')),
  url(r'^', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from __future__ import unicode_literals
from django.db import models
import markdown
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class CourseQuerySet(models.QuerySet):
  def visible(self):
    return self.filter(events__datetime__gte=timezone.now()).distinct()

class Course(models.Model):
  title = models.CharField(
  	max_length = 200,
  	verbose_name = 'Short title',
  	help_text = 'Short title name for the course. Do not add any specific dates here.'
  )
  description = models.TextField(
  	verbose_name = 'Longer description',
  	help_text = 'Complete description of the course. May contain special markup. Do not add any specific dates here.'
  )
  image = ProcessedImageField(
  	upload_to = 'courses/',
    processors = [ResizeToFill(640, 480)],
    format = 'JPEG',
    options = {'quality': 90},
  	verbose_name = 'General image of the course',
  	help_text = 'Pick up a image file from your computer. Image should be big enough so that it wont get scaled up by the system.'
  )

  def __unicode__(self):
    return self.title

  objects = CourseQuerySet.as_manager()

  def description_html(self):
    return markdown.markdown(self.description, extensions=['markdown.extensions.nl2br'])

  def visible_events(self):
    return filter(lambda event: event.datetime >= timezone.now(), self.events.all())

class CourseEvent(models.Model):
  course = models.ForeignKey(Course,
    related_name = 'events',
    verbose_name = 'Course',
    help_text = 'Course that this event belongs to.'
  )
  datetime = models.DateTimeField(
  	verbose_name = 'Date & time',
  	help_text = 'When this event is planned to happen',
  )
  store_link = models.URLField(
  	verbose_name = 'Link to the web store',
  	help_text = 'Provide complete URL to the web store.'
  )

  def __unicode__(self):
  	return self.course + ': ' + self.datetime

  class Meta:
    ordering = ['datetime']

courses/forms.py
from django import forms
from .models import *

class CourseForm(forms.ModelForm):

  class Meta:
    model = Course
    fields = ('title', 'description', 'image')
    widgets = {
      'title': forms.TextInput(
        attrs = { 'class': 'form-control' }
      ),
      'description': forms.Textarea(
        attrs = {
          'class': 'form-control',
          'rows': 15,
        }
      )
    }

EventFormSet = forms.inlineformset_factory(Course, CourseEvent,
  fields = ('datetime', 'store_link'),
  widgets = {
    'datetime': forms.TextInput(
      attrs = {
        'class': 'form-control',
        'placeholder': 'VVVV-KK-PP TT:MM'
      }
    ),
    'store_link': forms.TextInput(
      attrs = {
        'class': 'form-control'
      }
    )
  }
)

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

@login_required
def admin_index(request):
  if request.method == 'POST':
    form = CourseForm(request.POST, request.FILES)
    event_formset = EventFormSet(request.POST)

    if form.is_valid() and event_formset.is_valid():
      form.save()
      event_formset.save()

      messages.success(request, 'New course created!')

      return redirect(reverse('courses:admin_index'))
    else:
      messages.error(request, 'New course not saved!')
  else:
    form = CourseForm()
    event_formset = EventFormSet()

  return render(request, 'courses/admin/index.html', {
    'form': form,
    'event_formset': event_formset,
    'courses': Course.objects.all(),
  })

@login_required
def admin_edit(request, pk):
  course = get_object_or_404(Course, pk=pk)

  if request.method == 'POST':
    form = CourseForm(request.POST, request.FILES, instance=course)
    event_formset = EventFormSet(request.POST, instance=course)

    if form.is_valid() and event_formset.is_valid():
      form.save()
      event_formset.save()

      messages.success(request, 'Course saved!')

      return redirect(reverse('courses:admin_index'))
    else:
      messages.error(request, 'Course not saved!')
  else:
    form = CourseForm(instance=course)
    event_formset = EventFormSet(instance=course)

  return render(request, 'courses/admin/edit.html', {
    'form': form,
    'event_formset': event_formset,
    'course': course
  })

@login_required
def admin_delete(request, pk):
  course = get_object_or_404(Course, pk=pk)

  if request.method == 'POST':
    course.delete()
    messages.success(request, 'Course deleted!')

    return redirect(reverse('courses:admin_index'))

  raise Http404('Not a POST request')

def index(request):
  return render(request, 'courses/index.html', {
    'courses': Course.objects.visible()
  })

def show(request, pk):
  return render(request, 'courses/show.html', {
    'course': get_object_or_404(Course, pk=pk)
  })

courses/templates/courses/admin/edit.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Edit course <em>{{ course.title }}</em></h1>
<hr />

<div class="row">
  <div class="col-xs-12">
    <form class="pull-right" method="POST" action="{% url 'courses:admin_delete' pk=course.pk %}">
      {% csrf_token %}
      <input class="btn btn-xs btn-danger" type="submit" value="Delete" />
    </form>
  </div>
</div>

<form method="POST" enctype="multipart/form-data">
  {% include 'courses/admin/form.html' with form=form %}
</form>
{% endblock %}

courses/templates/courses/admin/form.html
{% csrf_token %}

<div class="row">
	<div class="col-xs-12">
	  {% include 'kury/form/input_block.html' with field=form.title %}
	  {% include 'kury/form/input_block.html' with field=form.description %}
	  {% include 'kury/form/input_block.html' with field=form.image %}
	</div>
</div>

<br />
<h3>Course events</h3>
<hr />

{{ event_formset.management_form }}
{% for event_form in event_formset %}
	<h4>Event #{{ forloop.counter }}</h4>
	<div class="row">
		{{ event_form.id }}
		<div class="col-xs-4">
      {% include 'kury/form/input_block.html' with field=event_form.datetime %}
    </div>
    <div class="col-xs-4">
      {% include 'kury/form/input_block.html' with field=event_form.store_link %}
		</div>
		<div class="col-xs-4">
		  <div class="checkbox">
		  	<br />
		    <label>
		      {{ event_form.DELETE }} Delete?
		    </label>
		  </div>
		</div>
	</div>
{% endfor %}

<div class="row">
	<div class="col-xs-12">
	  <br />
	  <input class="btn btn-primary" type="submit" value="Save" />
	</div>
</div>

courses/templates/courses/admin/index.html
{% extends 'kury/admin_layout.html' %}

{% block content %}

<br />
<h1>Courses</h1>
<hr />

<div class="col-xs-12">
  {% if courses|length > 0 %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Events</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
          <tr>
            <td>{{ course.title }}</td>
            <td>{{ course.description|truncatewords:10 }}</td>
            <td>
              {% for event in course.events.all %}
                {{ event.datetime|date:'SHORT_DATETIME_FORMAT' }},
              {% empty %}
                <em>No events so far.</em>
              {% endfor %}
            </td>
            <td>
              <a href="{% url 'courses:admin_edit' pk=course.pk %}">Edit</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-center">No courses yet. Create one below!</p>
  {% endif %}
  <br />
</div>

<h2>Create new course</h2>
<hr />

<form method="POST" enctype="multipart/form-data">
  {% include 'courses/admin/form.html' with form=form %}
</form>

{% endblock %}